2-logic: use if and switch to perform a calculation
MastersAcademy/js-course-2022 pull request #114
Opened 2022-11-27 14:38 UTC by trueanqu

Use if and switch operators

Sorry for the missed deadline, let the PR be here for historical reasons.

Take care!

2022-12-02 19:13 UTC, TArch64 commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +const readline = require('readline').createInterface({
зазвичай імпорти описують зверху і не змішують з кодом

```js
const readline = require('interface');
const interface = readline.createInterface
```

2022-12-02 19:13 UTC, TArch64 commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +        readline.question('Enter operation: ', (operation) => {
Було б логічніше запитати перше число, операцію а потім друге число

2022-12-03 09:18 UTC, trueanqu commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +const readline = require('readline').createInterface({
зробив імпорт окремою операцією

2022-12-03 09:18 UTC, trueanqu commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +        readline.question('Enter operation: ', (operation) => {
змінено порядок

2022-12-03 18:12 UTC, TArch64 commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +        rl.question('Enter second number: ', (secondNumInput) => {
Уникай скорочень в назвах оскільки це ускладнює розуміння коду в рази. це можливо не замітно зараз але потім це стає критичним

2022-12-03 20:21 UTC, trueanqu commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +        rl.question('Enter second number: ', (secondNumInput) => {
змінив так, щоб пакет, який заімпортив називався скороченням, бо лише раз використовується. Сутність, яка працюватиме з консоллю тепер називається більш зрозуміло

2022-12-04 16:59 UTC, TArch64 requested changes

2022-12-04 16:59 UTC, TArch64 commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +const readline = rl.createInterface({
Ти замінив скорочення нази в одному місці на скорочення в іншому. Таке не підходить. Потрібно вміти правильно називати речі. Це 60% адекватного коду

2022-12-05 19:54 UTC, TArch64 commented on homeworks/bohdan.oblapenko_trueanqu/2-logic/logic.js
> +const readline = readlineModule.createInterface({
цей варіант прийму, але все ще можна було краще. Старайся брати назви з тих речей які в коді називаються. Бібліотека називається `readline` тому зазвичай зміну так же само називають. В цієї бібліотеки є метод `readline.createInterface` тому логічно буде що змінну назвати краще `readlineInterface`

2022-12-05 19:54 UTC, TArch64 approved these changes

2022-12-05 19:54 UTC, merged