Added second homework (2-logic)
MastersAcademy/js-course-2022 pull request #116
Opened 2022-11-28 12:46 UTC by certat1um

2022-12-02 14:26 UTC, certat1um commented on homeworks/ivan.kononenko_certat1um/2-logic/logic.js
> +//         result = firstNumber +-secondNumber;
Случайно вийшло, зараз переправлю

2022-12-02 21:20 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.kononenko_certat1um/2-logic/logic.js
> +//         result = firstNumber +-secondNumber;
Розкоменти код (але так щоб він працював), або розбий на декілька файлів

2022-12-03 09:48 UTC, volodymyr-ustilkin-moc commented
Розкоментуй код (але так щоб він працював), або розбий на декілька файлів.

2022-12-03 20:08 UTC, volodymyr-ustilkin-moc requested changes

2022-12-03 20:08 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.kononenko_certat1um/2-logic/if-else.js
> +
тут else немає, на випадок, якщо буде некоректний оператор

2022-12-03 20:08 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.kononenko_certat1um/2-logic/switch-case.js
> +        result = null;
У тебе result і так дорівнює null у 3му рядку, для чого ти його ще раз присваюєшь? Виведи краще, якесь повідомлення, що невірний оператор.

2022-12-08 20:55 UTC, TArch64 commented
@certat1um @volodymyr-ustilkin-moc Привіт. Потрібно щось зробити з цим пулл реквестом. Дедлайн як на мене давно вже пройшов

2022-12-09 09:58 UTC, closed without merging