added read.md
MastersAcademy/js-course-2022 pull request #12
Opened 2022-11-02 01:09 UTC by olgadobrodii

added read.md

2022-11-03 14:21 UTC, volodymyr-ustilkin-moc requested changes
Переглянь будь-ласка уважніше завдання, П.4
Додайте нову папку **до /homeworks**...

2022-11-04 00:30 UTC, olgadobrodii commented
Перенесла папку до homeworks
шлях home/olha/js-course-2022-main/homeworks/olha.dobrodii_olgadobrodii/homeworks/0-intro
вірно зрозуміла?

чт, 3 нояб. 2022 г. в 16:21, volodymyr-ustilkin-moc <
***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Переглянь будь-ласка уважніше завдання, П.4
> Додайте нову папку *до /homeworks*...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MastersAcademy/js-course-2022/pull/12#pullrequestreview-1167004317>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH2MCWQVMQN7YECM52UUS63WGPC5PANCNFSM6AAAAAARUSXKHI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-04 08:41 UTC, volodymyr-ustilkin-moc commented
У тебе зараз в реквесті шлях до файлу такий: `homeworks/0-intro/README.md`
Між `homeworks` і `0-intro` має бути ще одна папка по шаблону з п.4 `<ім'я>.<прізвище>_<ім'я користувача github>`

2022-11-04 22:37 UTC, olgadobrodii commented
Виправила та запушила зміни.
Перенесла папку до homeworks
шлях ...homeworks/olha.dobrodii_olgadobrodii//0-intro

Дякую за відповідь(пояснення)

пт, 4 нояб. 2022 г. в 10:41, volodymyr-ustilkin-moc <
***@***.***>:

> У тебе зараз в реквесті шлях до файлу такий: homeworks/0-intro/README.md
> Між homeworks і 0-intro має бути ще одна папка по шаблону з п.4 <ім'я>.<прізвище>_<ім'я
> користувача github>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MastersAcademy/js-course-2022/pull/12#issuecomment-1303123340>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH2MCWW5OYCVYLLHADKG4S3WGTD2RANCNFSM6AAAAAARUSXKHI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-05 12:56 UTC, mzabolotnev-liveperson approved these changes

2022-11-05 12:56 UTC, mzabolotnev-liveperson approved these changes

2022-11-05 12:58 UTC, volodymyr-ustilkin-moc approved these changes

2022-11-05 12:58 UTC, merged