add-functions.js-and-HW-solution
MastersAcademy/js-course-2022 pull request #172
Opened 2022-12-08 17:34 UTC by Andrey-Shtanko

2022-12-08 18:18 UTC, Andrey-Shtanko commented
я не знаю що я накрутив, чому з'явився в коміті пекедж-лок файл... і не знаю як це виправити тепер

2022-12-08 18:26 UTC, Andrey-Shtanko commented
повернув той файл назад

2022-12-09 12:10 UTC, TArch64 requested changes

2022-12-09 12:10 UTC, TArch64 commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +    }
В рекурсії краще робити ретурн як можна раніше щоб виконувати менше операцій

2022-12-09 12:10 UTC, TArch64 commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +    return resultWeightOfProduct;
Дуже довга назва + створення константи тут не потібно
```suggestion
    return weight * liquid * count;
```

2022-12-09 12:10 UTC, TArch64 commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +    return result;
```suggestion
    return num * getNumberInDegree(num, deg - 1);
```

2022-12-09 13:07 UTC, Andrey-Shtanko commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +const MERCURY = 1355;
Все пофікшено в останньому комміті

2022-12-09 13:07 UTC, Andrey-Shtanko commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +const liquidValue = 1;
Все пофікшено в останньому комміті

2022-12-09 13:08 UTC, Andrey-Shtanko commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +    }
Все пофікшено в останньому комміті

2022-12-09 13:09 UTC, Andrey-Shtanko commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +    return resultWeightOfProduct;
Все пофікшено в останньому комміті

2022-12-09 13:09 UTC, Andrey-Shtanko commented on homeworks/andriy.shtanko_Andrey-Shtanko/3-functions/functions.js
> +    return result;
Все пофікшено в останньому комміті

2022-12-10 11:57 UTC, TArch64 approved these changes

2022-12-10 11:57 UTC, merged