3 functions
MastersAcademy/js-course-2022 pull request #179
Opened 2022-12-09 11:37 UTC by learningtogetherua

hw to 3-d leсtion

2022-12-09 14:49 UTC, volodymyr-ustilkin-moc requested changes

2022-12-09 14:49 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +const mercuryTankVol = 1000;
Глобальні константи бажано писати капсом і снейк кейсом, наприклад `WATER_TANK_VOL`.
В задачі вони каким же чином написані
const OIL = 926;
const WATER = 1000;
const MERCURY = 1355;

2022-12-09 14:49 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +// const mercuryLiquidWeight=getWeight(mercury1KLitersWeight,mercuryTankVol, mercuryTankQuantity)
тут навколо знака зорівнює пробілу нехватає

2022-12-09 14:49 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +// Вивід загальної ваги рідин всіх типів
Якщо хочеш зробити другим способом -- зроби краще в окремому файлі, щоб не було зайвих коментарів

2022-12-09 14:49 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +    return oneTypeLiquidWeight;
![image](https://user-images.githubusercontent.com/98042101/206727043-902bc239-d1dd-4339-842e-65d047234df8.png)
Тут можна зразу повертати результат 'return (weight / 1000) * liquid * count;'

2022-12-09 14:49 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +let summaryWeight = 0;
summaryWeight на мою думку краще перенести трохи нижче (поставити перед першим використанням), бо вона у тебе використовується лише в одній області в коді

2022-12-09 16:19 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +const mercuryTankVol = 1000;
Змінив як у завданні, без снейку( _ ), бо до цього вже скорочував змінні по зауваженню, що рядки з ними довше 100 символів. Якщо додам довші назви зі снейккейсом, знов полізе за 100

2022-12-09 16:21 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +let summaryWeight = 0;
На лекції радили по максимуму те що глобально юзається прописувати на початку програми

2022-12-09 16:22 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +// const mercuryLiquidWeight=getWeight(mercury1KLitersWeight,mercuryTankVol, mercuryTankQuantity)
довжину рядка не пропустить

2022-12-09 16:23 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +    return oneTypeLiquidWeight;
в лекції показували що непогана практика писати в змінну а потім її повертати

2022-12-09 16:24 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +// Вивід загальної ваги рідин всіх типів
наступного разу зроблю окремо. Поки вважаю це не принциповим, в принципі завдання другий варіант робити не було, тож можна ігнорувати коментарі)

2022-12-10 08:41 UTC, volodymyr-ustilkin-moc requested changes

2022-12-10 08:41 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +    return oneTypeLiquidWeight;
Тоді поясни для чого ця змінна? Де ти ще її використовуєш? Із мінусів -- це зайвий рядок. А які плюси від неї?

2022-12-10 08:41 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +let summaryWeight = 0;
summaryWeight -  у тебе використовується не глобально, а тільки в одній області програми

2022-12-10 08:41 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +// Вивід загальної ваги рідин всіх типів
> наступного разу зроблю окремо. Поки вважаю це не принциповим, в принципі завдання другий варіант робити не було, тож можна ігнорувати коментарі)

По 'наступного разу зроблю окремо' -- тоді домашку прийму наступного разу )
Такі речі на проектах ускладнюють читання коду

2022-12-10 11:47 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/3-functions/functions.js
> +// const mercuryLiquidWeight=getWeight(mercury1KLitersWeight,mercuryTankVol, mercuryTankQuantity)
Тоді розбий на декілька рядків

2022-12-11 18:02 UTC, volodymyr-ustilkin-moc approved these changes

2022-12-11 18:02 UTC, merged