hw#3
MastersAcademy/js-course-2022 pull request #186
Opened 2022-12-09 20:04 UTC by KaterinaTkach

this is HW #3

2022-12-10 12:01 UTC, MZabolotnev requested changes

2022-12-10 12:01 UTC, MZabolotnev commented on homeworks/katerina.tkach_KaterinaTkach/3-functions/functions.js
> +// eslint-disable-next-line consistent-return
Не можна дізейблити ніяких eslint правил.

2022-12-10 12:01 UTC, MZabolotnev commented on homeworks/katerina.tkach_KaterinaTkach/3-functions/functions.js
> +// eslint-disable-next-line max-len
Те саме. Перенось на інші рядки, форматуй код.

2022-12-11 12:46 UTC, MZabolotnev requested changes

2022-12-11 12:46 UTC, MZabolotnev commented on homeworks/katerina.tkach_KaterinaTkach/3-functions/functions.js
> +    return true; // <<< this is a bad fix
Використай if, else if, else замість трьох if, і бедфікс стане не потрібен.

2022-12-11 12:46 UTC, MZabolotnev commented on homeworks/katerina.tkach_KaterinaTkach/3-functions/functions.js
> +// eslint-disable-next-line no-shadow
Видали будь ласка непотрібні коменти. Не треба дізейблити правила, треба переіменувати змінну tanks в  const getAWeight = (tanks) , тому що в тебе вже є змінна tanks оголошена вище.

2022-12-11 12:46 UTC, MZabolotnev commented on homeworks/katerina.tkach_KaterinaTkach/3-functions/functions.js
> +// console.log(getAllWeight(tanks));
Видали будь ласка непотрібні коменти.

2022-12-11 15:35 UTC, KaterinaTkach commented
@MZabolotnev ++

2022-12-11 15:37 UTC, MZabolotnev approved these changes

2022-12-11 15:37 UTC, merged