3-functions
MastersAcademy/js-course-2022 pull request #189
Opened 2022-12-10 01:48 UTC by Academik1986

2022-12-10 03:16 UTC, Academik1986 commented
Тарас EsLint не пропускає:   Error:   13:23  error  'weightOfOilTanker' is already declared in the upper scope on line 5 column 7       no-shadow, пише отаку помилку гуглив пише що потрібно відключити no-shadow

2022-12-10 11:02 UTC, TArch64 commented
Ні, відключати нічого не потрібно. Тут детальніше про це правило
https://eslint.org/docs/latest/rules/no-shadow

2022-12-10 12:17 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +const getWeightOil = (weightOfOilTanker, liquid, amountOfOilTanker) => {
Штука функцій в тому що ти можеш перевикористовувати один і той же самий код з різними параметрами. У завданні сказано що має бути тільки одна функція і вона має обчислювати всі можливі типи рідин

2022-12-10 12:18 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +    return 'Enter liquid';
Вона може працювати і з іншими рідинами

2022-12-10 12:19 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +const amountOfMercuryTanker = 2;
1. Краще уникати of у назвах
2. краще замість amount слово count. Перше в англійській означає неперелічувану кількість

```suggestion
const oilTankerWeight = 926;
const waterTankerWeight = 1000;
const mercuryTankerWeight = 1355;

const oilTankerCount = 3;
const waterTankerCount = 5;
const mercuryTankerCount = 2;
```

2022-12-10 12:21 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +}
загальна маса має вираховуватися на основі попередніх викликів функцій. Бо інакше тобі тут потрібно повторити той же самий код

2022-12-10 12:21 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +}
Намагайся робити менше повторень в коді

2022-12-11 14:09 UTC, TArch64 requested changes

2022-12-11 14:09 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +    return `Загальна маса рідини: ${getTotalWeight()} кг`;
ця функція все ще робить 2 різних операції. Вирахоування ваги рідини та вираховування загальної маси рідин

2022-12-11 14:09 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +};
1. В цій функції немає сенсу бо можна взяти значення напряму
2. ця змінна все ще вираховувається окремо, а не на основі попередніх даних. Ти щойно зробив функція яка вираховує масу окремої рідини. Для чого цей код потрібно повторювати ще раз?

2022-12-11 14:11 UTC, TArch64 requested changes

2022-12-11 14:11 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +const MERCURY = 1.355;
Назви мають казати що вони в собі зберігають. Вона має бути така щоб коли ти десь її побачив то зрозумів що там навіть не розуміючи контекста

2022-12-11 14:11 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +const oneCistern = 1000;
одна цистерна що? Інформація про те що це одна не несе за собою багато сенсу тому можна прибрати з назви. При тому у тебе немає інформації що означає ця цифра. Вага? Обʼєм? Відстань між молекулами хімічної сполуки?

2022-12-11 14:32 UTC, Academik1986 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +    return `Загальна маса рідини: ${getTotalWeight()} кг`;
то на вираховування загальної маси рідини зробити просто іншу функцію чи як?

2022-12-11 14:35 UTC, TArch64 commented
По коміт месседах має бути зрозуміло що за зміни там. Через пів року подивившись на оці ти зможеш сказати які тут були зміни?

<img width="364" alt="image" src="https://user-images.githubusercontent.com/29049264/206909858-d25a7990-5438-4e95-9f99-83657d0a7d82.png">

2022-12-11 16:27 UTC, TArch64 commented
Дуже багато деталей) Також якщо тобі потрібно потрібно обʼєднувати різні зміни в один комміт меседж то розілити ці зміни в 2 комміта. Тут таке ж як і з функціями

<img width="644" alt="image" src="https://user-images.githubusercontent.com/29049264/206915836-c713b265-cd17-4c2c-8517-a246c6a21720.png">

2022-12-11 16:32 UTC, Academik1986 commented
> Дуже багато деталей) Також якщо тобі потрібно потрібно обʼєднувати різні зміни в один комміт меседж то розілити ці зміни в 2 комміта. Тут таке ж як і з функціями
> 
Згоден!

2022-12-11 16:49 UTC, TArch64 requested changes

2022-12-11 16:49 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +const totalWeightOneTank = 1000;
Це не вага бо вагу тобі потрібно вирахувати

2022-12-11 16:49 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +    return `Загальна маса рідини: ${totalLiquid}`;
ця функція все ще відповідає за 2 операції одночасно. Вона вираховує вагу однієї рідини чи всіх разом?

2022-12-11 16:49 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +const totalLiquid = totaOilWeight + totaWaterWeight + totaMercuryWeight;
У тебе уже є функція яка обраховуває вагу кожної рідини. Навіщо тобі писати тут цю логіку ще раз? Чому не можна використати результат попередніх викликів?

2022-12-11 16:50 UTC, TArch64 commented
Месседж комміта взагалі не відповідає змінах всередині нього

<img width="688" alt="image" src="https://user-images.githubusercontent.com/29049264/206917038-6a1c7579-eccf-4209-9e45-884a97635ed9.png">

2022-12-11 16:51 UTC, TArch64 requested changes

2022-12-11 16:51 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +const mercuryTanker = 1.355;
що таке танкер? їх кількість? Що означають ці цифри які тут записані

2022-12-12 00:28 UTC, Academik1986 commented
Error:   10:43  error  Expected to return a value at the end of arrow function  consistent-return
Гуглив проблему додавав  else {return false} тоді Lint пише що else лишній

2022-12-12 20:47 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +    }
Навіщо тут потрібна ця перевірка?

2022-12-12 22:26 UTC, Academik1986 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +    }
> Навіщо тут потрібна ця перевірка?

дійшло виправив

2022-12-12 23:20 UTC, Academik1986 commented on homeworks/serhii.buhaichuk_Academik1986/3-functions/functions.js
> +    }
> > Навіщо тут потрібна ця перевірка?
> 
> дійшло виправив, дякую

2022-12-13 13:06 UTC, TArch64 approved these changes

2022-12-13 13:07 UTC, merged