4 objects
MastersAcademy/js-course-2022 pull request #213
Opened 2022-12-16 13:31 UTC by learningtogetherua

hw 4 tamagochi object

2022-12-17 18:47 UTC, DrSmile444 requested changes
@learningtogetherua 
Please, fix ESLint errors.

2022-12-19 19:37 UTC, volodymyr-ustilkin-moc requested changes
В задачі сказано, що треба зробити методи що збільшують 1 із показників та зменшують інші. Де такі методи для `healthLevel, hungryLevel, sleepLevel`?

2022-12-19 19:37 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +    increase() {
Де використовується даний метод?

2022-12-19 19:37 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +        return false;
Такі вирази можна робити одним рядком:
`return this.healthLevel > 0;`

2022-12-19 19:41 UTC, volodymyr-ustilkin-moc requested changes

2022-12-19 19:41 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +}
За 15 викликів гра закінчитья 6 раз замість 1 -- де перевірка на завершення гри?
![image](https://user-images.githubusercontent.com/98042101/208506526-d8084f05-852c-4717-a79d-cc17ac1037e4.png)

2022-12-20 05:35 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +    increase() {
Цітую: "Ви повинні створити функції для обʼєкту, які будуть або збільшувати, або зменшувати показники."
Тож функції, множина. У мене їх дві. Немає в завданні що до кожного окрему функцію. В моїх двох функціях змінюються в різній пропорції кожен показник. Такий геймплей, дбаєш/не дбаєш=зменшується/не зменшується.

Стосовно використання метода. Про це взагалі жодного слова немає. Бо це ще не сама гра, а просто створення об'єкту для гри. Тож навіть цикл що перевіряє він вже виходить за межі завдання.

2022-12-20 05:49 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +        return false;
Незрозуміло. Маєте на увазі запропонований рядок вставити в дужки if(сюди)?

2022-12-20 05:51 UTC, learningtogetherua commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +}
Ок, видалю цю частину. Бо це виходить за межі завдання "створити об'єкт"

2022-12-20 13:42 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +        return false;
Твої 4 строчки роблять теж саме, що і одна моя.

2022-12-20 13:43 UTC, volodymyr-ustilkin-moc commented on homeworks/ivan.shykhat-sarkisov_learningtogetherua/4-objects/objects.js
> +    increase() {
Ти витягнуввав із контексту. Ось скрін з таски, я виділив необхідне
![image](https://user-images.githubusercontent.com/98042101/208680502-ad89fc5f-3eec-4a23-a938-855c14a82116.png)

2022-12-20 13:43 UTC, closed without merging