Homework 4 Objects
MastersAcademy/js-course-2022 pull request #220
Opened 2022-12-17 11:04 UTC by Sobchenko-dev

@MZabolotnev

2022-12-17 12:17 UTC, MZabolotnev requested changes

2022-12-17 12:17 UTC, MZabolotnev commented on homeworks/oleksandr.sobchenko_Sobchenko-dev/4-objects/objects.js
> +// console.log(tamagochi);
Видали коммент, будь ласка

2022-12-17 15:36 UTC, Sobchenko-dev reviewed
@MZabolotnev

2022-12-20 18:07 UTC, MZabolotnev approved these changes

2022-12-21 16:18 UTC, merged