Homework 4 - Objects
MastersAcademy/js-course-2022 pull request #224
Opened 2022-12-17 23:39 UTC by K1Koff

Created a tamagochi console.log game

2022-12-18 18:56 UTC, volodymyr-ustilkin-moc requested changes

2022-12-18 18:56 UTC, volodymyr-ustilkin-moc commented on homeworks/roman.kit_K1Koff/4-objects/objects.js
> +        this.happiness += 1 * this.metabolism;
Для чого тут множення на 1 ?

2022-12-18 19:27 UTC, K1Koff commented on homeworks/roman.kit_K1Koff/4-objects/objects.js
> +        this.happiness += 1 * this.metabolism;
Кожне значення при виконанні функції множиться на коефіцієнт metabolism
Якщо по стандарту k = 1, при використанні метода feed до ситості додається 2.5 * k = 2.5.
При зміні k на 0.5 :
 2.5 * 0.5, додасться 1.25.
Така ж сама логіка і з параметром happiness. В даному випадку при штатному k = 1, це і правда не має сенсу, але при зміні k на 0.5, є.
k - своєрідний вибір складності гри.
При меншому k складність підвищується, так як damage() наносить відносно більший урон чим  feed()/heal()/play() на одиницю часу, і навпаки.

2022-12-19 09:01 UTC, volodymyr-ustilkin-moc commented
Напиши будь ласка коли закінчиш -- бо ти коміти робиш, в той час коли я перевіряю

2022-12-19 09:09 UTC, K1Koff commented
> Напиши будь ласка коли закінчиш -- бо ти коміти робиш, в той час коли я перевіряю

Реді

2022-12-19 09:22 UTC, volodymyr-ustilkin-moc approved these changes

2022-12-19 09:22 UTC, merged