4-objects
MastersAcademy/js-course-2022 pull request #226
Opened 2022-12-18 10:01 UTC by eAmolchanov

2022-12-18 14:59 UTC, TArch64 commented on homeworks/Anatolii.Molchanov_eAmolchanov/4-objects/objects.js
> +    },
Додай ще якісь дії

2022-12-18 15:00 UTC, TArch64 commented on homeworks/Anatolii.Molchanov_eAmolchanov/4-objects/objects.js
> +        this.happinessDown();
Чому всі 3 показники знижуються? За логікою щось має збільшуватися а щось знижуватися

2022-12-18 20:05 UTC, eAmolchanov commented on homeworks/Anatolii.Molchanov_eAmolchanov/4-objects/objects.js
> +    },
done

2022-12-18 20:05 UTC, eAmolchanov commented on homeworks/Anatolii.Molchanov_eAmolchanov/4-objects/objects.js
> +        this.happinessDown();
done

2022-12-19 21:43 UTC, TArch64 requested changes

2022-12-19 21:43 UTC, TArch64 commented on homeworks/Anatolii.Molchanov_eAmolchanov/4-objects/objects.js
> +    },
Зазвичай у тамагочі немає активностей які нічого не зменшують. Суть в тому щоб викликати правильні методи і балансувати між показниками

2022-12-19 21:43 UTC, TArch64 commented on homeworks/Anatolii.Molchanov_eAmolchanov/4-objects/objects.js
> +    },
Не дуже розумію для чого ці функції. Я б краще замість них написав інкремент та декремент прямо у функціях play та eat

2022-12-20 13:21 UTC, TArch64 approved these changes

2022-12-20 13:21 UTC, merged