Tamagochi
MastersAcademy/js-course-2022 pull request #231
Opened 2022-12-19 00:17 UTC by Academik1986

2022-12-19 21:47 UTC, TArch64 requested changes

2022-12-19 21:47 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/4-objects/tamagochi.js
> +tamagochi1['favorite eat'] = 'cookies';
Як на мене замало логіки для завдання із зірочкою. Наприклад можеш додати щоб можна було вказувати якою їжою його годувати і якщо це його улюблена то він буде отримувати додаткові очки

2022-12-19 21:47 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/4-objects/tamagochi.js
> +tamagochi2['favorite drink'] = 'pineapple juice';
Намагайся уникати створення полів з пробілами. У 85% випадків потрібно завжди діставати та записувати значення через крапочку, а не квадратні дужки як тут

2022-12-19 21:47 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/4-objects/tamagochi.js
> +tamagochi1['favorite eat'] = 'cookies';
І краще щоб це було розширення логіки з попереднього файлику, а не зовсім новий тамагочі

2022-12-19 21:57 UTC, Academik1986 commented on homeworks/serhii.buhaichuk_Academik1986/4-objects/tamagochi.js
> +tamagochi2['favorite drink'] = 'pineapple juice';
> Намагайся уникати створення полів з пробілами. У 85% випадків потрібно завжди діставати та записувати значення через крапочку, а не квадратні дужки як тут

ти маєш на увазі просто краще писати наприклад: tamagochi.favoriteEat?

2022-12-19 22:29 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/4-objects/tamagochi.js
> +tamagochi2['favorite drink'] = 'pineapple juice';
Так. Але краще `favoriteFood`

2022-12-20 03:16 UTC, Academik1986 commented on homeworks/serhii.buhaichuk_Academik1986/4-objects/tamagochi.js
> +tamagochi2['favorite drink'] = 'pineapple juice';
Зрозуміло! Переробив логіку додав функцію! Принаймні так я це все бачу, тож перевірь будь ласка. В любому випадку якщо з задачею із зірочкою знову щось буде не так то тоді вже не бери її до уваги)....

2022-12-20 13:16 UTC, TArch64 approved these changes

2022-12-20 13:16 UTC, merged