arrays
MastersAcademy/js-course-2022 pull request #245
Opened 2022-12-22 21:28 UTC by vikusik96

2022-12-24 14:14 UTC, TArch64 requested changes

2022-12-24 14:14 UTC, TArch64 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +const defayltArray = [
```suggestion
const defaultArray = [
```

2022-12-24 14:14 UTC, TArch64 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +    getStars.map((array) => hungDecorations(array));
Намагайся не використовувати дієслова у назвах змінних бо вони зазвичай використовуються у функціях і це може конфюзити інших розробників

2022-12-24 14:14 UTC, TArch64 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +    return array.map((el) => (el < 5 ? ' ' : '*'));
У стрілочних функціях можна не писати круглі дужки, окрім тих випадків коли ти повертаєш літерал обʼєкта
```suggestion
    return array.map((el) => el < 5 ? ' ' : '*');
```

2022-12-24 14:14 UTC, TArch64 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +    const result = array;
Дай такі назви array та result щоб було зрозуміло які дані там лежать. Також не певен що є сенс робити змінну result загалом

2022-12-24 14:14 UTC, TArch64 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +    convertArraysInStrings.map((el) => console.log(el));
`.map` має використовувати **тільки** для того щоб змінити елемент масиву та повернути новий масив. Тут же ти робиш виклик консолі -- це називається side effect і таких штук потрібно уникати в map. Якщо тобі потрібно просто вивести дані то використай `.forEach` або `for..of` цикл

2022-12-24 14:14 UTC, TArch64 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +    return result;
Коли користуєшся `.map` то намагайся уникати мутацій оригінальних даних. Якщо простіше то в `.map` ти повертаєш новий елемент масиву із усіма змінами, але при цьому оригінальні дані не мають змінитися. Часто іммутабельність даних допомогає уникнути не зрозумілої поведінки в подальшому. Це більш зрозумілий підхід та більш передбачуваний

2022-12-25 08:15 UTC, vikusik96 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +    return array.map((el) => (el < 5 ? ' ' : '*'));
![image](https://user-images.githubusercontent.com/113469081/209461247-902b9ca5-521e-4f41-b251-6162849ff406.png)
ругаэться eslint без дужок(((

2022-12-25 14:23 UTC, TArch64 commented on homeworks/viktoriia.sedyk_vikusik96/5-arrays/arrays.js
> +    return array.map((el) => (el < 5 ? ' ' : '*'));
Окей, тоді най буде

2022-12-26 16:11 UTC, TArch64 approved these changes

2022-12-26 16:11 UTC, merged