5 arrays
MastersAcademy/js-course-2022 pull request #256
Opened 2022-12-25 23:54 UTC by Academik1986

2022-12-26 16:10 UTC, TArch64 requested changes

2022-12-26 16:10 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/5-arrays/arrays.js
> +        }
замість буков використовуй такі назви щоб було зрозуміло що цей цикл робить

2022-12-26 16:10 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/5-arrays/arrays.js
> +let star = '';
Твоя функція пише значення в змінні глобальний скоупа -- такого намагайся уникати. Намагайся щоб вони було самодостатні бо інакше будуть проблеми якщо ти захочеш її в новий файл перенести + це збільшує шанс що хтось з ними щось зробить і поламає твою функцію

2022-12-26 16:10 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/5-arrays/arrays.js
> +christmasTree(10);
намагайся використовувати в назвах функцій дієслова

2022-12-26 16:10 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/secondtask.js
> +});
те ж саме з неймінгом тут. Використовуй такий неймінг щоб було зрозуміло що кожен кусочок робить

2022-12-26 18:48 UTC, Academik1986 commented on homeworks/serhii.buhaichuk_Academik1986/5-arrays/arrays.js
> +let star = '';
тобто ти маєш на увазі що цикл має бути самодостатнім та містити всі змінні в середині себе? Так?

2022-12-26 18:59 UTC, TArch64 commented on homeworks/serhii.buhaichuk_Academik1986/5-arrays/arrays.js
> +let star = '';
Так

2022-12-26 21:54 UTC, Academik1986 commented
Підправив!

2022-12-27 12:56 UTC, TArch64 approved these changes

2022-12-27 12:56 UTC, merged