0 intro
MastersAcademy/js-course-2022 pull request #27
Opened 2022-11-03 18:45 UTC by MatviienkoOleh

1-homework

2022-11-04 10:48 UTC, MZabolotnev requested changes
Є лишні файли в реквесті

2022-11-04 12:02 UTC, MatviienkoOleh commented
Добрий день , можете під казати які саме ?


пт, 4 нояб. 2022 г. в 12:49, Miron Zabolotniev ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Є лишні файли в реквесті
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MastersAcademy/js-course-2022/pull/27#pullrequestreview-1168305516>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANWLCD7OPGPDPXOXAGYSLDTWGTS2BANCNFSM6AAAAAARWOCVZI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-04 14:00 UTC, MatviienkoOleh commented
Тепер зрозумів що package-lock.json був не потрібний в реквесті.

2022-11-05 13:21 UTC, MZabolotnev requested changes
Так, але він все рівно є в реквесті.

2022-11-05 14:30 UTC, MatviienkoOleh commented
That was last try ) need to learn the git properly

2022-11-06 13:30 UTC, MZabolotnev commented
Подивись у вкладку Files changed - там три файла змінені. ПР має включати лише твій файл з твоім завданням, і не змінювати нічого іншого.

2022-11-06 13:30 UTC, closed without merging