6-async
MastersAcademy/js-course-2022 pull request #275
Opened 2023-01-12 23:13 UTC by AndriiMorozov88

2023-01-14 21:12 UTC, TArch64 requested changes

2023-01-14 21:12 UTC, TArch64 commented on homeworks/andrii.morozov_AndriiMorozov88/6-async/async.js
> +function showPokemon(random = 'Game Start') {
чому у аргументорі `random` значення `Game Start`?

2023-01-14 21:12 UTC, TArch64 commented on homeworks/andrii.morozov_AndriiMorozov88/6-async/async.js
> +function showPokemon(random = 'Game Start') {
Загалом не розумію сенс аргумента рандом

2023-01-14 21:12 UTC, TArch64 commented on homeworks/andrii.morozov_AndriiMorozov88/6-async/async.js
> +let failedProperty;
Все це обовʼязково збегати в глобальному скоупі? Цим менше даних доступних всім тим краще

2023-01-15 11:09 UTC, AndriiMorozov88 commented on homeworks/andrii.morozov_AndriiMorozov88/6-async/async.js
> +let failedProperty;
Прибрав з глобального скоупа failedProperty. Все інше на мою думку повинно бути в глобальному

2023-01-15 15:27 UTC, TArch64 approved these changes

2023-01-15 15:27 UTC, merged