7- class
MastersAcademy/js-course-2022 pull request #303
Opened 2023-01-20 19:31 UTC by IgorFromUA

2023-01-20 21:55 UTC, volodymyr-ustilkin-moc requested changes

2023-01-20 21:55 UTC, volodymyr-ustilkin-moc commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/wheel.js
> +        this.wheelArray = wheelArray.fill(wheel, 0, 4);
А не простіше замість цього написати щось типу `this.wheelArray = [wheel, wheel, wheel, wheel];` ?

2023-01-20 21:55 UTC, volodymyr-ustilkin-moc commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/dimensions.js
> +    setwidth(width) {
setwidth => setWidth

2023-01-20 21:55 UTC, volodymyr-ustilkin-moc commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/dimensions.js
> +    setHeigth(height) {
Опечатка Heigth => Height

2023-01-20 21:55 UTC, volodymyr-ustilkin-moc commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/dimensions.js
> +        this.length = length;
Методи з 1 рядка, а вони точно треба? Думаю, краде такі речі в конструкторі сетити?

2023-01-20 21:55 UTC, volodymyr-ustilkin-moc commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/class.js
> +
Абзаци бажано ставити між різними блоками коду і перед return якщо він не перший в блоці... Тобто між const вони не треба

2023-01-20 22:23 UTC, volodymyr-ustilkin-moc requested changes

2023-01-20 22:23 UTC, volodymyr-ustilkin-moc commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/class.js
> +console.log(car);
Вивід даних, бажано в порядок привести, особливо це стосується wheelArray
![image](https://user-images.githubusercontent.com/98042101/213813781-66d54d08-3ce1-4810-9bdf-a930e441d60b.png)

Метод console.log викликає метод toString у об'єкта/класа, а як його немає, то старається хоч щось вивести 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString
Приклад трохи підправив, щоб він на класах був
![image](https://user-images.githubusercontent.com/98042101/213815453-aedd1298-f8d3-45ad-8576-08f6bb59d72b.png)

2023-01-20 23:39 UTC, IgorFromUA commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/dimensions.js
> +        this.length = length;
взагалі хотів спробувати сетери і гетери, щоб була можливість потім змінювати екземпляри класу(прокачали двигун і змінити потужність), але щось невиходить навіть звичайними методами(. 
перепишу як краще.

2023-01-21 09:41 UTC, volodymyr-ustilkin-moc approved these changes

2023-01-21 10:05 UTC, volodymyr-ustilkin-moc commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/dimensions.js
> +        this.length = length;
Написав в телеграмі

2023-01-21 15:15 UTC, IgorFromUA commented on homeworks/ihor.zapisochnyy_IgorFromUA/7-class/dimensions.js
> +        this.length = length;
виправив

2023-01-22 09:40 UTC, merged