Homework 1
MastersAcademy/js-course-2022 pull request #79
Opened 2022-11-17 17:24 UTC by hisbvdis

2022-11-17 21:28 UTC, TArch64 requested changes

2022-11-17 21:28 UTC, TArch64 commented on homeworks/roma.zvarich_hisbvdis/1-basics/basics.js
> +const exponentiation = a ** b;
Додай сюди трохи операцій із рядками. Наприклад можеш відформатувати виведення чисел

2022-11-18 10:25 UTC, hisbvdis commented on homeworks/roma.zvarich_hisbvdis/1-basics/basics.js
> +const exponentiation = a ** b;
Добавил конкатенацию строк с числами при выведении результата в `console.log()`

2022-11-18 12:07 UTC, TArch64 approved these changes

2022-11-18 12:07 UTC, TArch64 commented on homeworks/roma.zvarich_hisbvdis/1-basics/basics.js
> +const bio = `${String(index)} ${firstName} ${lastName}: ${String(age)}`;
Загалом можна не приводити дані до типу стрінг коли робиш інтерполяцію, бо js робить це автоматично сам

2022-11-18 12:08 UTC, merged