1-basics (task)
MastersAcademy/js-course-2022 pull request #89
Opened 2022-11-18 01:51 UTC by buzyaka

2022-11-18 09:08 UTC, MZabolotnev requested changes

2022-11-18 09:08 UTC, MZabolotnev commented on homeworks/vladislav.buzunar_buzyaka/1-basics/basics.js
> +// (thirdNumber % secondNumber);
А що це за комменти? Повидаляй не важливі комментарі.

2022-11-18 13:32 UTC, buzyaka commented on homeworks/vladislav.buzunar_buzyaka/1-basics/basics.js
> +// (thirdNumber % secondNumber);
Я мав на увазi приклади застосування %, гаразд, зараз видалю!

2022-11-20 16:31 UTC, TArch64 commented
@buzyaka Користуйся гітом для того щоб оновлювати файли, а не кнопкою оновлення в гітхабі. В подальшому такі пулл реквести будемо закривати

2022-11-20 20:15 UTC, buzyaka commented
> @buzyakaКористуйся гітом для того, чтобы ововлювати файлы, а не кнопкою ововлення в гітхабі. В подольшом такі пулл реквестио будем закрывать

да, хорошо, научусь и применю знания на сдаче второго и остальных дз, спасибо!

2022-11-20 21:35 UTC, MZabolotnev approved these changes

2022-11-20 21:35 UTC, merged